### ISSUE TITLE
Bug: Python 3 not supported

### ISSUE THREAD

**Issue by abhisharma404** [OWASP/SecureTea-Project#21]
While trying & testing, I ran to the following bug:

**Command executed** : `sudo python3 SecureTea.py`

```
Traceback (most recent call last):
  File "SecureTea.py", line 8, in <module>
    from securetea.core import SecureTea
  File "/home/abhisharma404/GSoC_OWASP/p6/SecureTea-Project/securetea/__init__.py", line 2, in <module>
    from . import core
  File "/home/abhisharma404/GSoC_OWASP/p6/SecureTea-Project/securetea/core.py", line 20, in <module>
    from securetea.secureTeaTelegram import SecureTeaTelegram
  File "/home/abhisharma404/GSoC_OWASP/p6/SecureTea-Project/securetea/secureTeaTelegram.py", line 35
    self.logger = logger.SecureTeaLogger(
                                        ^
TabError: inconsistent use of tabs and spaces in indentation
```
However, the code seems to work fine when executed in Python 2.

I've tried playing it around, but after every fix there is an EOF error.

**Development Environment :**
```
Python version : 3.6
OS : Ubuntu 18.04 LTS
```

**Comment by rejahrehim** [comment]
[Line 29 in Telegram File](https://github.com/OWASP/SecureTea-Project/blob/5facc64aa828a67abb2cb4f260d2ac97ef106cbf/securetea/secureTeaTelegram.py#L29)
Has mixed tab and spaces for indentation.

**Comment by rejahrehim** [comment]
@mishal23
