### ISSUE TITLE
Error After setting up Configuration

### ISSUE THREAD

**Issue by kevinshaji97** [OWASP/SecureTea-Project#249]
**Error after setting up the configuration using terminal (Traceback)**

**To Reproduce**
1.  Run python3 SecureTea.py
2. Set up the configurations via Terminal 

**Error Code**
```
Traceback (most recent call last):
  File "SecureTea.py", line 13, in <module>
    secT = SecureTea()
  File "/home/k***/ven2/SecureTea-Project/securetea/core.py", line 325, in __init__
    self.cred['debug']
  File "/home/k***/ven2/SecureTea-Project/securetea/lib/notifs/secureTeaTwitter.py", line 54, in __init__
    self.id = self.getuserid()
  File "/home/k***/ven2/SecureTea-Project/securetea/lib/notifs/secureTeaTwitter.py", line 72, in getuserid
    return response['id']
```
**Screenshots**
![Screenshot from 2019-12-07 15-25-22](https://user-images.githubusercontent.com/46342897/70372636-aad87780-1907-11ea-94b9-f12bf757240c.jpg)

**Desktop:**
 - Operating System: Ubuntu
 - OS version:  18.04

**Comment by abhisharma404** [comment]
@kevinshaji97 Turns out a problem in retrieving JSON details, have you used the correct Twitter credentials?

**Comment by kevinshaji97** [comment]
Yes I've used the correct twitter credentials

**Comment by adeyosemanputra** [comment]
@prince-7  also @pwned-17 please check it

**Comment by prince-7** [comment]
This issue might be caused because of not using the correct python version. Use python3.6.0.
