### ISSUE TITLE
sqlite3 DB Error

### ISSUE THREAD

**Issue by Tikam02** [OWASP/SecureTea-Project#52]
Bug - Database Error

**To Reproduce**
1. Start Vurtualenv
2. cd SecureTea-Project
3. run - sudo python SecureTea.py
4. sqlite3.OperationalError: unable to open database file

**Expected behavior**
To run the SecureTea.py by running : 
```python SecureTea.py```

**Screenshots**
```
(mlenv) tikam@Hal:~/ML/github/SecureTea-Project$ sudo python SecureTea.py
Traceback (most recent call last):
  File "SecureTea.py", line 8, in <module>
    from securetea.core import SecureTea
  File "/home/tikam/ML/github/SecureTea-Project/securetea/__init__.py", line 2, in <module>
    from . import core
  File "/home/tikam/ML/github/SecureTea-Project/securetea/core.py", line 17, in <module>
    from securetea import configurations
  File "/home/tikam/ML/github/SecureTea-Project/securetea/configurations.py", line 17, in <module>
    from securetea import logger
  File "/home/tikam/ML/github/SecureTea-Project/securetea/logger.py", line 17, in <module>
    connection = sqlite3.connect('/etc/securetea/db.sqlite3')
sqlite3.OperationalError: unable to open database file


```

**Desktop (please complete the following information):**
 - OS:  Ubuntu 18
- Environement - Python3

**Comment by abhisharma404** [comment]
Can you try running using Python 3, `sudo python3 SecureTea.py`. Could be a Python 2 specific error.
Also try reinstalling from scratch. 

Have a look at the following link:
https://stackoverflow.com/questions/4636970/sqlite3-operationalerror-unable-to-open-database-file

>> Is the disk containing /tmp full? (You're on Unix, so use df /tmp to find out.)
>> Does the /tmp/cer directory have “odd” permissions? (SQLite needs to be able to create additional files in it in order to handle things like the commit log.)

**Comment by Tikam02** [comment]
@abhisharma404  It's Same 
```
user@root:~/ML/github/SecureTea-Project$ sudo python3 SecureTea.py
[sudo] password for tikam: 
Traceback (most recent call last):
  File "SecureTea.py", line 8, in <module>
    from securetea.core import SecureTea
  File "/home/tikam/ML/github/SecureTea-Project/securetea/__init__.py", line 2, in <module>
    from . import core
  File "/home/tikam/ML/github/SecureTea-Project/securetea/core.py", line 17, in <module>
    from securetea import configurations
  File "/home/tikam/ML/github/SecureTea-Project/securetea/configurations.py", line 17, in <module>
    from securetea import logger
  File "/home/tikam/ML/github/SecureTea-Project/securetea/logger.py", line 17, in <module>
    connection = sqlite3.connect('/etc/securetea/db.sqlite3')
sqlite3.OperationalError: unable to open database file

```
