### ISSUE TITLE
Bug: Lost support for Python 3 & failing test cases

### ISSUE THREAD

**Issue by abhisharma404** [OWASP/SecureTea-Project#65]
Here is the error that I'm getting while executing the command: `sudo python3 SecureTea.py`
Clearly, urllib2 deprecation in Python 3 is causing the error.
```
Traceback (most recent call last):
  File "SecureTea.py", line 8, in <module>
    from securetea.core import SecureTea
  File "/home/abhisharma404/GSoC_OWASP/p27/SecureTea-Project/securetea/__init__.py", line 2, in <module>
    from . import core
  File "/home/abhisharma404/GSoC_OWASP/p27/SecureTea-Project/securetea/core.py", line 18, in <module>
    from urllib2 import urlopen
ModuleNotFoundError: No module named 'urllib2'
```
Apart from this there are 10 failing test cases specific for Python 3:
```
platform linux -- Python 3.6.5, pytest-3.5.1, py-1.5.3, pluggy-0.6.0
rootdir: /home/abhisharma404/GSoC_OWASP/p27/SecureTea-Project, inifile:
plugins: remotedata-0.2.1, openfiles-0.3.0, doctestplus-0.1.3, arraydiff-0.2
collected 0 items / 10 errors                                                  

==================================== ERRORS ====================================
_____________________ ERROR collecting test/test_common.py _____________________
ImportError while importing test module '/home/abhisharma404/GSoC_OWASP/p27/SecureTea-Project/test/test_common.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
test/test_common.py:3: in <module>
    from securetea import common
securetea/__init__.py:2: in <module>
    from . import core
securetea/core.py:18: in <module>
    from urllib2 import urlopen
E   ModuleNotFoundError: No module named 'urllib2'
_________________ ERROR collecting test/test_configurations.py _________________
ImportError while importing test module '/home/abhisharma404/GSoC_OWASP/p27/SecureTea-Project/test/test_configurations.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
test/test_configurations.py:3: in <module>
    from securetea import configurations
securetea/__init__.py:2: in <module>
    from . import core
securetea/core.py:18: in <module>
    from urllib2 import urlopen
E   ModuleNotFoundError: No module named 'urllib2'
_____________________ ERROR collecting test/test_engine.py _____________________
ImportError while importing test module '/home/abhisharma404/GSoC_OWASP/p27/SecureTea-Project/test/test_engine.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
test/test_engine.py:3: in <module>
    from securetea.lib.firewall import engine
securetea/__init__.py:2: in <module>
    from . import core
securetea/core.py:18: in <module>
    from urllib2 import urlopen
E   ModuleNotFoundError: No module named 'urllib2'
________________ ERROR collecting test/test_firewall_monitor.py ________________
ImportError while importing test module '/home/abhisharma404/GSoC_OWASP/p27/SecureTea-Project/test/test_firewall_monitor.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
test/test_firewall_monitor.py:3: in <module>
    from securetea.lib.firewall.firewall_monitor import FirewallMonitor
securetea/__init__.py:2: in <module>
    from . import core
securetea/core.py:18: in <module>
    from urllib2 import urlopen
E   ModuleNotFoundError: No module named 'urllib2'
_________________ ERROR collecting test/test_packet_filter.py __________________
ImportError while importing test module '/home/abhisharma404/GSoC_OWASP/p27/SecureTea-Project/test/test_packet_filter.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
test/test_packet_filter.py:3: in <module>
    from securetea.lib.firewall.packet_filter import PacketFilter
securetea/__init__.py:2: in <module>
    from . import core
securetea/core.py:18: in <module>
    from urllib2 import urlopen
E   ModuleNotFoundError: No module named 'urllib2'
________________ ERROR collecting test/test_secureTeaHeaders.py ________________
ImportError while importing test module '/home/abhisharma404/GSoC_OWASP/p27/SecureTea-Project/test/test_secureTeaHeaders.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
test/test_secureTeaHeaders.py:3: in <module>
    from securetea.lib.security_header import secureTeaHeaders
securetea/__init__.py:2: in <module>
    from . import core
securetea/core.py:18: in <module>
    from urllib2 import urlopen
E   ModuleNotFoundError: No module named 'urllib2'
_________________ ERROR collecting test/test_secureTeaSlack.py _________________
ImportError while importing test module '/home/abhisharma404/GSoC_OWASP/p27/SecureTea-Project/test/test_secureTeaSlack.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
test/test_secureTeaSlack.py:2: in <module>
    from securetea.lib.notifs.secureTeaSlack import SecureTeaSlack
securetea/__init__.py:2: in <module>
    from . import core
securetea/core.py:18: in <module>
    from urllib2 import urlopen
E   ModuleNotFoundError: No module named 'urllib2'
________________ ERROR collecting test/test_secureTeaTwilio.py _________________
ImportError while importing test module '/home/abhisharma404/GSoC_OWASP/p27/SecureTea-Project/test/test_secureTeaTwilio.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
test/test_secureTeaTwilio.py:2: in <module>
    from securetea.lib.notifs.secureTeaTwilio import SecureTeaTwilio
securetea/__init__.py:2: in <module>
    from . import core
securetea/core.py:18: in <module>
    from urllib2 import urlopen
E   ModuleNotFoundError: No module named 'urllib2'
________________ ERROR collecting test/test_secureTeaTwitter.py ________________
ImportError while importing test module '/home/abhisharma404/GSoC_OWASP/p27/SecureTea-Project/test/test_secureTeaTwitter.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
test/test_secureTeaTwitter.py:2: in <module>
    from securetea.lib.notifs.secureTeaTwitter import SecureTeaTwitter
securetea/__init__.py:2: in <module>
    from . import core
securetea/core.py:18: in <module>
    from urllib2 import urlopen
E   ModuleNotFoundError: No module named 'urllib2'
_____________________ ERROR collecting test/test_utils.py ______________________
ImportError while importing test module '/home/abhisharma404/GSoC_OWASP/p27/SecureTea-Project/test/test_utils.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
test/test_utils.py:3: in <module>
    from securetea.lib.firewall import utils
securetea/__init__.py:2: in <module>
    from . import core
securetea/core.py:18: in <module>
    from urllib2 import urlopen
E   ModuleNotFoundError: No module named 'urllib2'
!!!!!!!!!!!!!!!!!!! Interrupted: 10 errors during collection !!!!!!!!!!!!!!!!!!!
=========================== 10 error in 0.42 seconds ===========================
```

**Comment by abhisharma404** [comment]
Working on the fix.
